base: 'https://form-upload.ddev.site/'
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    locale: de-DE
    navigationTitle: Deutsch
    flag: de
    hreflang: ''
    websiteTitle: ''
rootPageId: 1
websiteTitle: ''
