services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

    # Fluid ViewHelpers (like core: tagged and autowired)
  BrezoIt\MultiFileUpload\ViewHelpers\:
      resource: '../Classes/ViewHelpers/*'
      public: true
      tags: ['fluid.viewhelper']

    # Extbase TypeConverter
  BrezoIt\MultiFileUpload\Mvc\Property\TypeConverter\MultiUploadedFileReferenceConverter:
      tags:
          - name: extbase.type_converter
            priority: 10
            target: TYPO3\CMS\Extbase\Domain\Model\FileReference
            sources: array,TYPO3\CMS\Core\Http\UploadedFile
